"use client";

import type { ReactNode } from "react";

type CaseRow = {
  case_id?: string;
  domain?: string;
  scenario?: string | null;
  expected_status?: string;
  expected_risk?: string;
  regulatory_document?: string | null;
  regulatory_section?: string | null;
  source_chunk_id?: string | null;
  compliance_requirement?: string | null;
  evidence?: string | null;
  result?: string;
  agreement?: string;
  reviewer_decision?: string;
  reviewer_notes?: string;
  ml_prediction?: {
    available?: boolean;
    compliance_status?: string;
    risk_category?: string;
    confidence?: number | null;
    status_probabilities?: Record<string, number>;
  };
  finace_rules?: {
    risk_level?: string;
    triggered_rules?: string[];
  };
  disagreement?: {
    pair?: string;
    category?: string;
    note?: string;
  };
  layers?: {
    regulatory_evidence?: Record<string, unknown>;
    ml_prediction?: Record<string, unknown>;
  };
};

function Badge({
  children,
  tone = "neutral",
}: {
  children: ReactNode;
  tone?: "neutral" | "good" | "warn" | "bad" | "info";
}) {
  const cls =
    tone === "good"
      ? "border-emerald-400/30 bg-emerald-500/10 text-emerald-300"
      : tone === "warn"
        ? "border-amber-400/30 bg-amber-500/10 text-amber-300"
        : tone === "bad"
          ? "border-rose-400/30 bg-rose-500/10 text-rose-300"
          : tone === "info"
            ? "border-sky-400/30 bg-sky-500/10 text-sky-300"
            : "border-white/15 bg-white/5 text-white/70";
  return (
    <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${cls}`}>
      {children}
    </span>
  );
}

function Field({ label, value }: { label: string; value?: ReactNode }) {
  if (value == null || value === "") return null;
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-white/35">{label}</p>
      <p className="mt-1 text-sm text-white/80 whitespace-pre-wrap break-words">{value}</p>
    </div>
  );
}

export function CaseDetailPanel({
  caseRow,
  mode = "grounding",
}: {
  caseRow: CaseRow | null;
  mode?: "grounding" | "robustness" | "comparison" | "human";
}) {
  if (!caseRow) {
    return (
      <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.02] p-6 text-sm text-white/40">
        Select a case to inspect regulatory evidence and the ML prediction.
      </div>
    );
  }

  const ml = caseRow.ml_prediction;
  const confidence =
    ml?.confidence != null
      ? `${(Number(ml.confidence) * 100).toFixed(1)}%`
      : ml?.compliance_status && ml.status_probabilities?.[ml.compliance_status] != null
        ? `${(Number(ml.status_probabilities[ml.compliance_status]) * 100).toFixed(1)}%`
        : null;

  const agreement =
    caseRow.agreement ||
    (caseRow.result === "correct"
      ? "agreement"
      : caseRow.result === "incorrect"
        ? "disagreement"
        : null);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <Badge tone="info">{caseRow.case_id || "case"}</Badge>
        {caseRow.domain ? <Badge>{caseRow.domain}</Badge> : null}
        {caseRow.result === "correct" ? <Badge tone="good">Correct</Badge> : null}
        {caseRow.result === "incorrect" ? <Badge tone="bad">Incorrect</Badge> : null}
        {agreement === "disagreement" ? <Badge tone="warn">Review Required</Badge> : null}
        {agreement === "agreement" && mode === "comparison" ? (
          <Badge tone="good">Agreement</Badge>
        ) : null}
      </div>

      <div className="rounded-2xl border border-teal-400/20 bg-teal-500/[0.06] p-4 space-y-3">
        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-teal-200/80">
          Regulatory Evidence
        </p>
        <p className="text-[11px] text-white/40">
          Source of truth — not generated by the ML model.
        </p>
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Regulatory document" value={caseRow.regulatory_document || undefined} />
          <Field label="Section / clause" value={caseRow.regulatory_section || undefined} />
          <Field label="Source chunk ID" value={caseRow.source_chunk_id || undefined} />
          <Field label="Expected status" value={caseRow.expected_status} />
          <Field label="Expected risk" value={caseRow.expected_risk} />
        </div>
        <Field label="Requirement" value={caseRow.compliance_requirement || undefined} />
        <Field label="Evidence" value={caseRow.evidence || undefined} />
        <Field label="Scenario" value={caseRow.scenario || undefined} />
      </div>

      <div className="rounded-2xl border border-sky-400/20 bg-sky-500/[0.06] p-4 space-y-3">
        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-sky-200/80">
          ML Prediction
        </p>
        <p className="text-[11px] text-white/40">Independent validation signal only.</p>
        <div className="grid gap-3 sm:grid-cols-3">
          <Field
            label="Compliance prediction"
            value={ml?.compliance_status?.replace(/_/g, " ") || "Unavailable"}
          />
          <Field label="Risk" value={ml?.risk_category || "—"} />
          <Field label="Confidence" value={confidence || "—"} />
        </div>
      </div>

      {mode === "comparison" && (
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 space-y-3">
          <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-white/45">
            ML vs Finace
          </p>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <Field label="Regulatory expectation" value={caseRow.expected_status} />
            <Field
              label="Finace assessment (rules risk)"
              value={caseRow.finace_rules?.risk_level || "—"}
            />
            <Field label="ML prediction" value={ml?.compliance_status || "—"} />
            <Field label="ML risk" value={ml?.risk_category || "—"} />
          </div>
          <Field label="Result" value={agreement === "disagreement" ? "Disagreement — Review Required" : "Agreement"} />
          {caseRow.disagreement?.note ? (
            <p className="text-[12px] text-white/45">{caseRow.disagreement.note}</p>
          ) : null}
          <p className="text-[12px] text-white/40">
            A disagreement does not automatically mean that either system is wrong. It identifies a
            case that may require further examination against the regulatory evidence.
          </p>
        </div>
      )}

      {mode === "human" && (
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 space-y-3">
          <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-white/45">
            Human Review
          </p>
          <Field
            label="Reviewer decision"
            value={(caseRow.reviewer_decision || "needs_review").replace(/_/g, " ")}
          />
          <Field label="Reviewer notes" value={caseRow.reviewer_notes || "—"} />
        </div>
      )}
    </div>
  );
}
