"""Cross-cutting controls (always evaluated)."""

CORE_RULES: list[dict] = [
    {
        "rule_id": "R001_NO_KYC",
        "name": "Missing KYC",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\bno\s+kyc\b", r"\bwithout\s+kyc\b", r"\bskip\s+kyc\b", r"\bminimal\s+kyc\b"],
        "requires_any": [
            r"\b(full|mandatory|complete|strong)?\s*kyc\b.*\b(in\s+place|enabled|implemented|added|present|done)\b",
            r"\b(have|has|with|using|added|implemented)\s+(full\s+)?kyc\b",
            r"\bkyc\s+(is\s+)?(complete|mandatory|enabled|implemented)\b",
        ],
        "flag": "KYC process appears missing or bypassed",
        "recommendation": "Implement mandatory full KYC before onboarding or activation.",
    },
    {
        "rule_id": "R002_P2P_CRYPTO",
        "name": "P2P Crypto Exposure",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\bp2p\b.*\bcrypto\b", r"\bcrypto\b.*\bp2p\b", r"\bvirtual\s+asset\b", r"\bvda\b"],
        "requires_any": [
            r"\baml\b",
            r"\banti[- ]money\b",
            r"\btransaction\s+monitoring\b",
            r"\benhanced\s+due\s+diligence\b",
            r"\bedd\b",
        ],
        "flag": "Potential high AML risk from P2P/crypto activity",
        "recommendation": "Add AML controls, enhanced due diligence, and transaction monitoring.",
    },
    {
        "rule_id": "R003_CROSS_BORDER_NO_FEMA",
        "name": "Cross-border Without FEMA Controls",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [
            r"\bcross[- ]border\b",
            r"\bforeign\s+transfer\b",
            r"\binternational\s+remittance\b",
            r"\boffshore\s+wallet\b",
        ],
        "requires_any": [
            r"\bfema\b",
            r"\bfx\s+compliance\b",
            r"\bforex\s+declaration\b",
            r"\bforex\s+compliance\b",
            r"\brbi\s+reporting\b",
        ],
        "flag": "Cross-border flow detected without explicit FEMA/FX compliance terms",
        "recommendation": "Add FEMA checks, regulatory reporting, and forex declaration workflow.",
    },
    {
        "rule_id": "R004_NO_GRIEVANCE",
        "name": "Missing Grievance Redressal",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [
            r"\bno\s+grievance\b",
            r"\bwithout\s+grievance\b",
            r"\bno\s+complaint\b",
            r"\bno\s+redressal\b",
        ],
        "requires_any": [
            r"\bgrievance\s+(redressal|process|mechanism)\b",
            r"\bcomplaint\s+handling\b",
            r"\b(have|has|with|added|implemented)\s+grievance\b",
            r"\bombudsman\b",
        ],
        "flag": "Grievance redressal/complaint handling appears absent",
        "recommendation": "Define grievance process with SLA, escalation matrix, and audit trail.",
    },
    {
        "rule_id": "R005_NO_AML_MONITORING",
        "name": "No AML / Transaction Monitoring",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [
            r"\bno\s+aml\b",
            r"\bwithout\s+aml\b",
            r"\bno\s+transaction\s+monitoring\b",
            r"\bwithout\s+monitoring\b",
        ],
        "requires_any": [
            r"\baml\b",
            r"\btransaction\s+monitoring\b",
            r"\bsuspicious\s+transaction\b",
            r"\bstr\b",
            r"\bctr\b",
        ],
        "flag": "AML or transaction monitoring not described",
        "recommendation": "Implement AML policy, STR/CTR workflows, and continuous monitoring.",
    },
    {
        "rule_id": "R006_DATA_LOCALIZATION_GAP",
        "name": "Data Storage / Localization Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [
            r"\bstore\s+data\s+outside\s+india\b",
            r"\boffshore\s+server\b",
            r"\bwithout\s+data\s+locali[sz]ation\b",
            r"\bforeign\s+cloud\s+only\b",
        ],
        "requires_any": [
            r"\bdata\s+locali[sz]ation\b",
            r"\bstored\s+in\s+india\b",
            r"\bindia\s+data\s+centre\b",
            r"\brbi\s+data\s+locali[sz]ation\b",
        ],
        "flag": "Payment data residency / localization not assured",
        "recommendation": "Document India storage, RBI data localization, and cross-border transfer controls.",
    },
    {
        "rule_id": "R007_NO_CONSENT_AUDIT",
        "name": "Missing Consent / Audit Trail",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [
            r"\bwithout\s+consent\b",
            r"\bno\s+audit\s+trail\b",
            r"\bno\s+logging\b",
            r"\bconsent\s+not\s+(taken|recorded)\b",
        ],
        "requires_any": [
            r"\bexplicit\s+consent\b",
            r"\baudit\s+trail\b",
            r"\bimmutable\s+log\b",
            r"\bconsent\s+(captured|recorded|stored)\b",
        ],
        "flag": "Customer consent or audit logging appears weak",
        "recommendation": "Capture consent artifacts and maintain tamper-evident audit logs.",
    },
    {
        "rule_id": "R008_CYBER_POLICY_GAP",
        "name": "Cyber Security Policy Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [
            r"\bno\s+cyber\s*(security)?\s*policy\b",
            r"\bwithout\s+cyber\s*(security)?\b",
            r"\bno\s+iso\s*27001\b",
        ],
        "requires_any": [
            r"\bcyber\s*security\s+policy\b",
            r"\biso\s*27001\b",
            r"\bpci[- ]dss\b",
            r"\binformation\s+security\b",
        ],
        "flag": "Cyber security framework not referenced",
        "recommendation": "Align with RBI cyber resilience framework and document IS policy.",
    },
    {
        "rule_id": "R009_BCP_DR_GAP",
        "name": "BCP / DR Not Documented",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [r"\b(no|without)\s+(bcp|business\s+continuity|disaster\s+recovery)\b", r"\bno\s+dr\s+drill\b"],
        "requires_any": [r"\bbusiness\s+continuity\b", r"\bdisaster\s+recovery\b", r"\bdr\s+site\b"],
        "flag": "BCP/DR for payment systems not described",
        "recommendation": "Maintain tested BCP/DR per RBI technology guidelines.",
    },
    {
        "rule_id": "R010_BOARD_OVERSIGHT",
        "name": "Board / Committee Oversight Gap",
        "risk_level": "LOW",
        "categories": [],
        "patterns": [r"\bno\s+board\s+oversight\b", r"\bwithout\s+audit\s+committee\b.*\bcompliance\b"],
        "requires_any": [r"\bboard\b.*\b(compliance|risk)\b", r"\baudit\s+committee\b", r"\bgovernance\b"],
        "flag": "Board-level compliance oversight not referenced",
        "recommendation": "Report payment compliance metrics to board/risk committee.",
    },
    {
        "rule_id": "R011_VENDOR_RISK",
        "name": "Third-Party / Vendor Risk Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [r"\bvendor\b.*\b(no|without)\s+(contract|audit)\b", r"\bunvetted\s+saas\b.*\bpayment\b"],
        "requires_any": [r"\bvendor\s+risk\b", r"\bthird[- ]party\s+audit\b", r"\bsla\b.*\bvendor\b"],
        "flag": "Third-party payment vendor risk management weak",
        "recommendation": "Due diligence and contractual controls on all payment vendors.",
    },
]
