_CTS = ["CTS", "GENERAL"]

CTS_RULES: list[dict] = [
    {
        "rule_id": "R_CTS_001_TRUNCATION_GAP",
        "name": "Cheque Truncation / Image Gap",
        "risk_level": "MEDIUM",
        "categories": _CTS,
        "patterns": [r"\bcheque\b.*\b(no|without)\s+truncation\b", r"\bphysical\s+only\s+cheque\b"],
        "requires_any": [r"\bcts\b", r"\bcheque\s+truncation\b", r"\bimage\s+clearing\b"],
        "flag": "CTS / cheque truncation controls not described",
        "recommendation": "Align with CTS image standards and RBI cheque truncation guidelines.",
    },
    {
        "rule_id": "R_CTS_002_NO_POSITIVE_PAY",
        "name": "Positive Pay Not Implemented",
        "risk_level": "MEDIUM",
        "categories": _CTS,
        "patterns": [r"\b(no|without)\s+positive\s+pay\b", r"\bcheque\b.*\bno\s+positive\s+pay\b"],
        "requires_any": [r"\bpositive\s+pay\b", r"\bcheck\s+positive\s+pay\b"],
        "flag": "Positive Pay / cheque confirmation not described",
        "recommendation": "Offer Positive Pay for high-value cheque issuance.",
    },
    {
        "rule_id": "R_CTS_003_FORGERY_CONTROLS",
        "name": "Cheque Fraud Controls Weak",
        "risk_level": "MEDIUM",
        "categories": _CTS,
        "patterns": [r"\bcheque\b.*\b(no|without)\s+(fraud|forgery)\s+control\b"],
        "requires_any": [r"\bforgery\b", r"\bfraud\s+detection\b", r"\bmicr\b", r"\bcts\s+validation\b"],
        "flag": "Cheque fraud / MICR validation not referenced",
        "recommendation": "Implement CTS validation, MICR checks, and fraud monitoring.",
    },
    {
        "rule_id": "R_CTS_004_STALE_CHEQUE",
        "name": "Stale / Post-Dated Cheque Controls",
        "risk_level": "LOW",
        "categories": _CTS,
        "patterns": [r"\baccept\s+stale\s+cheque\b", r"\bno\s+validity\s+check\b.*\bcheque\b"],
        "requires_any": [r"\bstale\s+cheque\b", r"\b3\s+month\b", r"\bpost[- ]dated\b"],
        "flag": "Cheque validity period controls weak",
        "recommendation": "Reject stale cheques per RBI validity norms.",
    },
    {
        "rule_id": "R_CTS_005_HIGH_VALUE_CTS",
        "name": "High-Value Cheque Dual Sign",
        "risk_level": "MEDIUM",
        "categories": _CTS,
        "patterns": [r"\bhigh\s+value\s+cheque\b.*\bsingle\s+sign", r"\bno\s+dual\s+sign\b.*\bcheque\b"],
        "requires_any": [r"\bdual\s+sign", r"\bjoint\s+mandate\b", r"\bmaker\s+checker\b.*\bcheque\b"],
        "flag": "High-value cheque authorization weak",
        "recommendation": "Require dual authorization for high-value cheque issuance.",
    },
]
