"""Fraud, AML, sanctions — cross-cutting (always evaluated)."""

FRAUD_AML_RULES: list[dict] = [
    {
        "rule_id": "R_FRAUD_001_SANCTIONS_SCREEN",
        "name": "Sanctions Screening Missing",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\b(no|without)\s+sanctions\s+screen", r"\bnot\s+screened\s+against\s+ofac\b"],
        "requires_any": [r"\bsanctions\s+screen", r"\bofac\b", r"\bun\s+list\b", r"\bpep\s+screen"],
        "flag": "Sanctions / PEP screening not described",
        "recommendation": "Screen customers and transactions against sanctions and PEP lists.",
    },
    {
        "rule_id": "R_FRAUD_002_STR_NOT_FILED",
        "name": "STR / Suspicious Reporting Gap",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\b(no|without)\s+str\b", r"\bsuspicious\s+transaction\b.*\bnot\s+report"],
        "requires_any": [r"\bstr\b", r"\bsuspicious\s+transaction\s+report", r"\bfiu\b"],
        "flag": "Suspicious transaction reporting workflow missing",
        "recommendation": "Define STR filing to FIU-IND with escalation SLAs.",
    },
    {
        "rule_id": "R_FRAUD_003_SMURFING",
        "name": "Structuring / Smurfing Risk",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\bsplit\s+transaction", r"\bstructuring\b", r"\bsmurfing\b", r"\bbelow\s+threshold\s+split"],
        "requires_any": [r"\baggregation\s+monitoring\b", r"\bpattern\s+detection\b", r"\baml\s+alert\b"],
        "flag": "Transaction splitting / structuring controls weak",
        "recommendation": "Detect linked small transfers and velocity anomalies.",
    },
    {
        "rule_id": "R_FRAUD_004_PHISHING_CONTROLS",
        "name": "Phishing / Social Engineering Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [r"\b(no|without)\s+phishing\s+awareness\b", r"\bcustomer\s+education\b.*\bnot\b"],
        "requires_any": [r"\bphishing\b", r"\bsocial\s+engineering\b", r"\bcustomer\s+awareness\b"],
        "flag": "Customer security awareness not referenced",
        "recommendation": "Run phishing awareness and OTP/PIN confidentiality campaigns.",
    },
    {
        "rule_id": "R_FRAUD_005_MULE_ACCOUNTS",
        "name": "Mule Account Monitoring Gap",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\bmule\s+account", r"\b(no|without)\s+mule\s+detection\b"],
        "requires_any": [r"\bmule\b", r"\baccount\s+takeover\b", r"\bbehavioral\s+analytics\b"],
        "flag": "Money mule / ATO monitoring not described",
        "recommendation": "Monitor inbound-outbound velocity and dormant account reactivation.",
    },
    {
        "rule_id": "R_FRAUD_006_CHARGE_FRAUD",
        "name": "Chargeback / Friendly Fraud Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [r"\b(no|without)\s+chargeback\s+monitor", r"\bfriendly\s+fraud\b.*\bignored\b"],
        "requires_any": [r"\bchargeback\b", r"\bfraud\s+rate\b", r"\bdispute\s+analytics\b"],
        "flag": "Chargeback fraud monitoring weak",
        "recommendation": "Track dispute ratios and merchant fraud thresholds.",
    },
    {
        "rule_id": "R_FRAUD_007_CDD_EDD",
        "name": "CDD / EDD Not Applied",
        "risk_level": "HIGH",
        "categories": [],
        "patterns": [r"\b(no|without)\s+(cdd|edd)\b", r"\bhigh[- ]risk\s+customer\b.*\bno\s+edd\b"],
        "requires_any": [r"\bcustomer\s+due\s+diligence\b", r"\bEDD\b", r"\benhanced\s+due\s+diligence\b"],
        "flag": "Risk-based CDD/EDD not described",
        "recommendation": "Apply enhanced due diligence for high-risk segments.",
    },
    {
        "rule_id": "R_FRAUD_008_RECORD_RETENTION",
        "name": "AML Record Retention Gap",
        "risk_level": "MEDIUM",
        "categories": [],
        "patterns": [r"\bdelete\s+transaction\s+logs\b", r"\b(no|short)\s+retention\b.*\baml\b"],
        "requires_any": [r"\bretention\b.*\b(year|pmla)\b", r"\b5\s+year\b", r"\brecord\s+keeping\b"],
        "flag": "AML record retention period unclear",
        "recommendation": "Retain KYC and transaction records per PMLA timelines.",
    },
]
