_NFS = ["NFS", "GENERAL"]

NFS_RULES: list[dict] = [
    {
        "rule_id": "R_NFS_001_ATM_SURCHARGE",
        "name": "ATM Surcharge / Disclosure Gap",
        "risk_level": "LOW",
        "categories": _NFS,
        "patterns": [r"\batm\b.*\b(hidden|no)\s+surcharge\s+disclosure\b", r"\bextra\s+fee\b.*\bnot\s+disclosed\b"],
        "requires_any": [r"\bsurcharge\s+disclosure\b", r"\brbi\s+atm\s+fee\b", r"\bfree\s+transaction\b"],
        "flag": "ATM fee / surcharge disclosure unclear",
        "recommendation": "Disclose NFS ATM charges per RBI guidelines.",
    },
    {
        "rule_id": "R_NFS_002_NO_PIN_SECURITY",
        "name": "ATM PIN / Card Security Gap",
        "risk_level": "HIGH",
        "categories": _NFS,
        "patterns": [r"\batm\b.*\b(share|store)\s+pin\b", r"\bcard\b.*\bno\s+pin\s+block\b"],
        "requires_any": [r"\bpin\s+(block|encryption)\b", r"\bchip\s+card\b", r"\bemv\b"],
        "flag": "ATM/card PIN security practices weak",
        "recommendation": "Enforce PIN confidentiality, EMV, and hotlisting procedures.",
    },
    {
        "rule_id": "R_NFS_003_NO_CASH_REPLENISHMENT_AUDIT",
        "name": "Cash Replenishment Audit Gap",
        "risk_level": "MEDIUM",
        "categories": _NFS,
        "patterns": [r"\bcash\s+replenish(ment)?\b.*\b(no|without)\s+audit\b"],
        "requires_any": [r"\bcash\s+replenishment\s+audit\b", r"\bcash\s+logistics\b", r"\bcit\b"],
        "flag": "ATM cash replenishment controls not described",
        "recommendation": "Audit CIT replenishment and reconcile cassette balances.",
    },
    {
        "rule_id": "R_NFS_004_SKIMMING",
        "name": "ATM Skimming / Shimming Controls",
        "risk_level": "HIGH",
        "categories": _NFS,
        "patterns": [r"\b(no|without)\s+anti[- ]skim", r"\batm\b.*\bno\s+inspection\b"],
        "requires_any": [r"\banti[- ]skim", r"\bterminal\s+inspection\b", r"\bjitter\b"],
        "flag": "ATM anti-skimming controls not described",
        "recommendation": "Inspect ATMs for skimming and deploy anti-tamper tech.",
    },
    {
        "rule_id": "R_NFS_005_WHTDR_LIMIT",
        "name": "ATM Withdrawal Limit Override",
        "risk_level": "MEDIUM",
        "categories": _NFS,
        "patterns": [r"\batm\b.*\b(unlimited|override)\s+withdrawal\b", r"\bbypass\s+daily\s+atm\s+limit\b"],
        "requires_any": [r"\bdaily\s+withdrawal\s+limit\b", r"\batm\s+cap\b"],
        "flag": "ATM withdrawal limits can be bypassed",
        "recommendation": "Enforce per-card daily ATM limits and alerts.",
    },
]
