"""PPI, wallets, stored value — overlaps UPI/GENERAL."""

_PPI = ["UPI", "GENERAL", "RBI_MD"]

PPI_WALLET_RULES: list[dict] = [
    {
        "rule_id": "R_PPI_001_CLOSED_LOOP",
        "name": "Closed-Loop PPI Without License",
        "risk_level": "HIGH",
        "categories": _PPI,
        "patterns": [r"\bclosed[- ]loop\b.*\bwallet\b", r"\bgift\s+card\b.*\bno\s+license\b"],
        "requires_any": [r"\bppi\s+license\b", r"\bprepaid\s+payment\s+instrument\b", r"\brbi\s+authorization\b"],
        "flag": "Closed-loop PPI may need RBI PPI license",
        "recommendation": "Classify instrument and obtain PPI license if required.",
    },
    {
        "rule_id": "R_PPI_002_LOAD_LIMIT",
        "name": "Wallet Load Limit Breach",
        "risk_level": "MEDIUM",
        "categories": _PPI,
        "patterns": [r"\bwallet\b.*\b(unlimited|exceed)\s+load\b", r"\bbypass\s+ppi\s+limit\b"],
        "requires_any": [r"\bload\s+limit\b", r"\bppi\s+cap\b", r"\bkyc\s+tier\b"],
        "flag": "PPI load limits not enforced in description",
        "recommendation": "Enforce RBI PPI balance caps by KYC level.",
    },
    {
        "rule_id": "R_PPI_003_CASH_OUT",
        "name": "PPI Cash-Out Prohibited Flow",
        "risk_level": "HIGH",
        "categories": _PPI,
        "patterns": [r"\bcash\s+out\b.*\bppi\b", r"\bwallet\b.*\bcash\s+withdrawal\b.*\bmerchant\b"],
        "requires_any": [r"\bno\s+cash\s+withdrawal\b", r"\bppi\s+restriction\b", r"\bclosed\s+loop\b"],
        "flag": "PPI cash-out may violate instrument rules",
        "recommendation": "Restrict cash withdrawal per PPI circular restrictions.",
    },
    {
        "rule_id": "R_PPI_004_INTEROPERABILITY",
        "name": "Wallet Interoperability Gap",
        "risk_level": "LOW",
        "categories": _PPI,
        "patterns": [r"\bwallet\b.*\b(non|not)\s+interoperable\b", r"\bsiloed\s+balance\b"],
        "requires_any": [r"\binteroperab", r"\bupi\s+transfer\b.*\bwallet\b", r"\bppi\s+interoperability\b"],
        "flag": "Wallet interoperability with UPI/banks unclear",
        "recommendation": "Support RBI/NPCI interoperability where mandated.",
    },
    {
        "rule_id": "R_PPI_005_EXPIRY_FUNDS",
        "name": "PPI Expiry / Dormancy Handling",
        "risk_level": "MEDIUM",
        "categories": _PPI,
        "patterns": [r"\bforfeit\s+customer\s+balance\b", r"\bexpir(e|y)\b.*\bwallet\b.*\bno\s+refund\b"],
        "requires_any": [r"\bdormant\s+account\b", r"\brefund\s+unspent\b", r"\bexpiry\s+policy\b"],
        "flag": "PPI balance expiry / dormancy policy unclear",
        "recommendation": "Follow RBI rules on PPI validity and customer refunds.",
    },
    {
        "rule_id": "R_PPI_006_FULL_KYC_WALLET",
        "name": "Full-KYC Wallet Not Required",
        "risk_level": "MEDIUM",
        "categories": _PPI,
        "patterns": [r"\bhigh\s+value\s+wallet\b.*\bmin\s+kyc\b", r"\b1\s+lakh\b.*\bwithout\s+full\s+kyc\b"],
        "requires_any": [r"\bfull\s+kyc\b", r"\bcomplete\s+kyc\b", r"\bkyc\s+upgrade\b"],
        "flag": "High-value wallet without full KYC",
        "recommendation": "Upgrade to full KYC before high balance or transfer limits.",
    },
    {
        "rule_id": "R_PPI_007_GIFT_PPI",
        "name": "Gift PPI Compliance Gap",
        "risk_level": "LOW",
        "categories": _PPI,
        "patterns": [r"\bgift\s+(card|ppi)\b.*\b(no|without)\s+issuer\b", r"\bopen\s+loop\s+gift\b"],
        "requires_any": [r"\bauthorized\s+issuer\b", r"\bgift\s+ppi\b.*\brbi\b"],
        "flag": "Gift PPI issuer authorization unclear",
        "recommendation": "Issue gift PPI only via licensed PPI issuer.",
    },
]
